### ISSUE TITLE
登录账号之后仍然无法访问里站

### ISSUE THREAD

**Issue by rakkasumi** [yuman07/EMHentai#1]
我需要怎么来提供log来帮助定位问题呢？

**Comment by yuman07** [comment]
你好，并不是有了里站账号就能查看里站内容
可参阅：https://nicebowl.fun/11
即里站账号的注册需要一定条件，且注册成功后也有大约2周左右的审核。
此时的账号是可以登录，但无法浏览

**Comment by rakkasumi** [comment]
大概不是账号问题吧？我从电脑浏览器上都是可以正常访问里站的
* 补充：Ehpanda是可以正常看到里站的

**Comment by yuman07** [comment]
hi，感谢反馈
排查是cookie同步bug，不清楚为什么之前的写法最近就抽风了
请拉取最新代码
