### ISSUE TITLE
如何安装应用

### ISSUE THREAD

**Issue by youliangh** [yuman07/EMHentai#2]
不知道如何安装应用，能说说大致步骤吗？

**Comment by yuman07** [comment]
1. Make sure you are currently using MacOS and have the latest versions of Xcode and Cocopods installed, and your mobile phone iOS version is greater than 13
2. Download Zip or git clone
3. open terminal
4. cd EMHenTai
5. pod install
6. open EMHenTai.xcworkspace
7. Run

**Comment by yuman07** [comment]
安装方式已经迁移到SwiftPM，具体参阅项目主页，还有问题可以继续提issue

**Comment by alphavvv** [comment]
请问没有mac有办法安装吗

**Comment by yuman07** [comment]
> 请问没有mac有办法安装吗

目前没有，因本人身处中国大陆，考虑EHentai相关法律风险，暂无直接提供安装包的计划，望理解

**Comment by alphavvv** [comment]
谢谢，那有可能提供几张预览图吗，想看看界面

**Comment by yuman07** [comment]
> 谢谢，那有可能提供几张预览图吗，想看看界面

已添加，请参阅项目主页
