### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Last-Remote** [yuman07/EMHentai#3]
新功能请求:
1.查看自己的favorite
2.首页thumbnail视图

bug:
刚开始可以用，但之后经常出现浏览器能上，但是APP里提示网络错误的情况

**Comment by yuman07** [comment]
1  这个可以，会排期开发
2  有点不理解，现在首页不也是有缩略图吗？请详细说明一下
3 「网络错误」请尝试更换节点

**Comment by Last-Remote** [comment]
就是说再加一个这种形式的排版
<img width="257" alt="image" src="https://user-images.githubusercontent.com/57584852/180418194-54e79671-6684-48b2-b63f-31fff9e0fcc1.png">

e站的网页版设置里就有5种排版可以选，选好保存首页就会变，你可以试下
<img width="668" alt="image" src="https://user-images.githubusercontent.com/57584852/180418927-e3b6ea30-679e-4783-9249-42a1e6ed4c06.png">

**Comment by yuman07** [comment]
抱歉，由于最近个人私事和工作上也有点忙，这两个feature的开发会慢一些，但会完成，请耐心等待，thx~
