### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by michaelyao98** [yuman07/EMHentai#4]
请问下作者能增加个cookie登录的功能吗？

**Comment by yuman07** [comment]
收到，会择期开发，感谢建议

**Comment by yuman07** [comment]
已经开发完毕，请拉取最新代码试用，如无问题三天后关闭此issue

**Comment by michaelyao98** [comment]
点击cookie登录显示这个：
EMHenTai[10437:1024979] [LayoutConstraints] Changing the translatesAutoresizingMaskIntoConstraints property of a UICollectionViewCell that is managed by a UICollectionView is not supported, and will result in incorrect self-sizing. View: <_UIAlertControllerTextFieldViewCollectionCell: 0x151dde6e0; frame = (0 0; 270 24); gestureRecognizers = <NSArray: 0x2811fb060>; layer = <CALayer: 0x281fcf220>>
提交cookie无反应也无输出。IOS15.6.1

**Comment by michaelyao98** [comment]
ipad点击登录按钮直接报异常闪退：
EMHenTai[34254:1553255] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x108808e00>) of style UIAlertControllerStyleActionSheet from EMHenTai.RootViewController (<EMHenTai.RootViewController: 0x10601f600>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:
(0x18046a288 0x19919a744 0x1831387ac 0x182a77a00 0x182f0a49c 0x182b77950 0x182a8ab4c 0x1059b0c70 0x1059b27c0 0x1059c2c68 0x1059c27a4 0x180422800 0x1803dc704 0x1803efbc8 0x19c55b374 0x182d63b58 0x182ae5090 0x198191ecc 0x104f1ed90 0x104f1ed1c 0x104f1ee6c 0x1057c9da4)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x108808e00>) of style UIAlertControllerStyleActionSheet from EMHenTai.RootViewController (<EMHenTai.RootViewController: 0x10601f600>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
terminating with uncaught exception of type NSException

**Comment by michaelyao98** [comment]
iphone可以正常使用，我exkey输错了，就是ipad点登录会闪退

**Comment by yuman07** [comment]
已经修复，请拉取最新代码

**Comment by michaelyao98** [comment]
可以正常使用，感谢作者
