### ISSUE TITLE
可以麻烦作者大大私发一份ipa不

### ISSUE THREAD

**Issue by 0316ng** [yuman07/EMHentai#5]
用黑苹果搞xcode没成功😂，可以在闲暇时间私发ipa到邮箱吗，麻烦作者大大了🙏
crazythuvme50@outlook.com

**Comment by yuman07** [comment]
不好意思，因为本人身处中国大陆，为了防止法律风险不能直接提供IPA

黑苹果理论上也是可以的，如果有编译相关问题可以问
